name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: npm install & set Version
      run: |
        npm version
        node -v
        npm ci
        npm config set git-tag-version false
        npm version ${{ github.event.release.tag_name }}

    - name: build
      run: npm run build
 
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: '${{ github.event.release.upload_url }}' 
        asset_path: ./node-red-contrib-renault-ze-${{ github.event.release.tag_name }}.tgz
        asset_name: node-red-contrib-renault-ze-${{ github.event.release.tag_name }}.tgz
        asset_content_type: application/zip

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x' 
        registry-url: 'https://registry.npmjs.org'

    - run: npm publish
      if: "!github.event.release.prerelease"      
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
